services:
  mysql:
    image: mysql:8.4
    container_name: workshop-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental_system

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: